name: ${project.name}
version: ${project.version}-b${build.number}
description: ${project.description}
api-version: 1.13

author: RobotoRaccoon
main: ${project.groupId}.${project.artifactId}.mMain
website: ${organization.url}

permissions:
  chatwarden.commands.staff:
    default: op
    description: People who can run staff commands.
  chatwarden.staff:
    default: op
    description: People who are treated as staff when moderating chat.
  chatwarden.player:
    default: true
    description: People who are affected by the plugin.

commands:
   chatwarden:
      description: Allows you to view reload the config.
      aliases: cw
      usage: |
        /<command> reload : Reload the config file.